### ISSUE TITLE
Question: How do you decided when the prompt end and where completion begins?

### ISSUE THREAD

**Issue by danielravina** [daveshap/GPT3_Finetunes#1]
Hello David,

I came here from your video [5 Tips and Misconceptions about Finetuning GPT-3](https://www.youtube.com/watch?v=VfAsu_dxw0g&list=TLPQMDkwODIwMjLMgQfVPnjy5g&index=2&ab_channel=DavidShapiro) 

You mentioned there to use Natural Language Separators. But in the [chatbot example](https://github.com/daveshap/GPT3_Finetunes/blob/main/Compassionate_Chatbot/chatbot.jsonl), the separator seems incoherent. Some completions are the last part of the conversation, some are in the middle. What is the reason for that and how does it make the results better?

The reason I'm asking is I'm building a bot that initiates the conversation with some information upfront (as opposed to the user starting out with a question). The bot is the driver of the conversion from beginning to end. What will be a good fine-tuning strategy or prompt engineering to accomplish that?

Thank you!

**Comment by daveshap** [comment]
You'll need to experiment. I have documented plenty of chatbots on youtube and their performance is self-evident. The reasoning is because of the format of prompting the model of who to speak next.
